backend:
  name: git-gateway
  branch: main # Егер репозиторийіңіз басқа бұтақта болса (мысалы, master), соны жазыңыз

media_folder: "public/images/uploads" # Суреттер сақталатын жер
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Жаңалықтар"
    folder: "content/news" # Мақалалар сақталатын папка
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Тақырыбы", name: "title", widget: "string" }
      - { label: "Шыққан күні", name: "date", widget: "datetime" }
      - { label: "Қысқаша сипаттама", name: "description", widget: "text" }
      - { label: "Негізгі сурет", name: "image", widget: "image", required: false }
      - { label: "Мәтін", name: "body", widget: "markdown" }